# Generated by Django 3.1.7 on 2021-03-28 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.subject'),
        ),
    ]
