# Generated by Django 3.1.7 on 2021-03-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210328_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegallery',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='preview_img',
            field=models.ImageField(blank=True, null=True, upload_to='subjects/images/', verbose_name='Subject Image'),
        ),
    ]
