services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"
    volumes:
      - ".:/code"
    environment:
      - "SECRET_KEY=ra2ugy9us17$$-_6by&@*+v*!t_8sjza!re2(7%%gl$$5ktabhds"
      - "DEBUG=0"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: